"""inicial: 10 tablas core

Revision ID: 01a3b1c2c693
Revises: 
Create Date: 2026-08-14 18:35:58.352395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01a3b1c2c693'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materials',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stock_current', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('stock_minimum', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('cost_per_unit', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('dimension_ancho_mm', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('dimension_espesor_mm', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('density', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('density_calibrada', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('external_links', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("unit IN ('kg','uds','m','litros')", name='ck_material_unit'),
    sa.CheckConstraint('density BETWEEN 100 AND 30000', name='ck_material_density'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_material_tenant_code')
    )
    op.create_index(op.f('ix_materials_tenant_id'), 'materials', ['tenant_id'], unique=False)
    op.create_table('orders',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('numero', sa.String(length=64), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('cliente', sa.String(length=255), nullable=True),
    sa.Column('fecha_entrega', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notas', sa.String(length=2000), nullable=True),
    sa.Column('real_material_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('real_total_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('estimado_total_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado IN ('draft', 'active', 'completed', 'cancelled')", name='ck_order_estado'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_numero'), 'orders', ['numero'], unique=False)
    op.create_index(op.f('ix_orders_tenant_id'), 'orders', ['tenant_id'], unique=False)
    op.create_table('tenant_features',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('users',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('stock_items',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.Column('lote', sa.String(length=100), nullable=False),
    sa.Column('coil_id', sa.String(length=100), nullable=True),
    sa.Column('cantidad_inicial', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('cantidad_disponible', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('width_mm', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('thickness_mm', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('coste_por_unidad', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('costing_method', sa.String(length=10), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('fecha_entrada', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_caducidad', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ubicacion', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=12), nullable=False),
    sa.Column('es_pico', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('creado_por', sa.Uuid(), nullable=True),
    sa.Column('heat_number', sa.String(length=100), nullable=True),
    sa.Column('grado_acero', sa.String(length=50), nullable=True),
    sa.Column('supplier_coil_id', sa.String(length=100), nullable=True),
    sa.Column('parent_coil_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(estado = 'pico') = es_pico", name='ck_stockitem_pico_consistente'),
    sa.CheckConstraint("estado IN ('activo', 'agotado', 'cuarentena', 'bloqueado', 'pico')", name='ck_stockitem_estado'),
    sa.CheckConstraint('coste_por_unidad >= 0', name='ck_stockitem_cost'),
    sa.CheckConstraint('thickness_mm IS NULL OR thickness_mm = 0 OR thickness_mm BETWEEN 0.1 AND 25', name='ck_stockitem_thickness'),
    sa.CheckConstraint('width_mm IS NULL OR width_mm = 0 OR width_mm BETWEEN 10 AND 2500', name='ck_stockitem_width'),
    sa.ForeignKeyConstraint(['creado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['parent_coil_id'], ['stock_items.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_items_coil_id'), 'stock_items', ['coil_id'], unique=False)
    op.create_index(op.f('ix_stock_items_grado_acero'), 'stock_items', ['grado_acero'], unique=False)
    op.create_index(op.f('ix_stock_items_heat_number'), 'stock_items', ['heat_number'], unique=False)
    op.create_index(op.f('ix_stock_items_material_id'), 'stock_items', ['material_id'], unique=False)
    op.create_index(op.f('ix_stock_items_tenant_id'), 'stock_items', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_stock_items_ubicacion'), 'stock_items', ['ubicacion'], unique=False)
    op.create_table('order_lines',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('linea_numero', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('modelo_id', sa.Uuid(), nullable=True),
    sa.Column('workstation_id', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('total_quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('produced_quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('target_material_qty', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('target_material_unit', sa.String(length=10), nullable=True),
    sa.Column('meters_per_piece', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('real_material_qty', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('real_material_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('real_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('scrap_material_qty', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('active_coil_id', sa.Uuid(), nullable=True),
    sa.Column('active_coil_code', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado IN ('pending', 'in_progress', 'stopped', 'completed')", name='ck_orderline_estado'),
    sa.ForeignKeyConstraint(['active_coil_id'], ['stock_items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'linea_numero', name='uq_orderline_numero')
    )
    op.create_index(op.f('ix_order_lines_order_id'), 'order_lines', ['order_id'], unique=False)
    op.create_table('coil_links',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('stock_item_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('order_line_id', sa.Uuid(), nullable=False),
    sa.Column('estado', sa.String(length=12), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado IN ('vinculada', 'consumida', 'retal', 'merma', 'desvinculada')", name='ck_coillink_estado'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['order_line_id'], ['order_lines.id'], ),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'stock_item_id', 'order_id', 'order_line_id', name='uq_coillink_burbuja')
    )
    op.create_table('material_consumos',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('order_line_id', sa.Uuid(), nullable=True),
    sa.Column('workstation_id', sa.String(length=100), nullable=False),
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.Column('stock_item_id', sa.Uuid(), nullable=True),
    sa.Column('lote', sa.String(length=100), nullable=True),
    sa.Column('consumed_quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('produced_quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('meters_per_piece', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('kg_por_pieza', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('calculation_method', sa.String(length=30), nullable=False),
    sa.Column('cost_per_unit', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('operator_id', sa.Uuid(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("calculation_method IN ('density_formula', 'model_override', 'meters_legacy', 'bom_static', 'manual', 'coil_end_scrap', 'manual_late_registration', 'none')", name='ck_consumo_calculation_method'),
    sa.CheckConstraint("tipo IN ('automatico', 'manual', 'ajuste', 'auto_audit', 'merma_puntas', 'salida_produccion')", name='ck_consumo_tipo'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['order_line_id'], ['order_lines.id'], ),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_consumos_order_id'), 'material_consumos', ['order_id'], unique=False)
    op.create_index(op.f('ix_material_consumos_tenant_id'), 'material_consumos', ['tenant_id'], unique=False)
    op.create_table('material_transactions',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.Column('stock_item_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('cantidad_anterior', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('cantidad_nueva', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('orden_id', sa.Uuid(), nullable=True),
    sa.Column('linea_orden_id', sa.Uuid(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('documento_referencia', sa.String(length=255), nullable=True),
    sa.Column('realizado_por', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tipo IN ('entrada_compra', 'salida_produccion', 'ajuste_inventario', 'merma', 'devolucion', 'reservado', 'merma_puntas', 'traslado')", name='ck_transaction_tipo'),
    sa.ForeignKeyConstraint(['linea_orden_id'], ['order_lines.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['orden_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['realizado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_transactions_material_id'), 'material_transactions', ['material_id'], unique=False)
    op.create_index(op.f('ix_material_transactions_tenant_id'), 'material_transactions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_transactions_tenant_id'), table_name='material_transactions')
    op.drop_index(op.f('ix_material_transactions_material_id'), table_name='material_transactions')
    op.drop_table('material_transactions')
    op.drop_index(op.f('ix_material_consumos_tenant_id'), table_name='material_consumos')
    op.drop_index(op.f('ix_material_consumos_order_id'), table_name='material_consumos')
    op.drop_table('material_consumos')
    op.drop_table('coil_links')
    op.drop_index(op.f('ix_order_lines_order_id'), table_name='order_lines')
    op.drop_table('order_lines')
    op.drop_index(op.f('ix_stock_items_ubicacion'), table_name='stock_items')
    op.drop_index(op.f('ix_stock_items_tenant_id'), table_name='stock_items')
    op.drop_index(op.f('ix_stock_items_material_id'), table_name='stock_items')
    op.drop_index(op.f('ix_stock_items_heat_number'), table_name='stock_items')
    op.drop_index(op.f('ix_stock_items_grado_acero'), table_name='stock_items')
    op.drop_index(op.f('ix_stock_items_coil_id'), table_name='stock_items')
    op.drop_table('stock_items')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('tenant_features')
    op.drop_index(op.f('ix_orders_tenant_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_numero'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_materials_tenant_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_table('tenants')
    # ### end Alembic commands ###
