"""feat(trace): tabla production_logs inmutable ISO 9001

Revision ID: fd6922f1785e
Revises: d7e9f2c4a1b3
Create Date: 2026-08-15 18:17:44.152364

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd6922f1785e"
down_revision: str | Sequence[str] | None = "d7e9f2c4a1b3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "production_logs",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("line_id", sa.Uuid(), nullable=False),
        sa.Column("operator_id", sa.Uuid(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("shift", sa.String(length=10), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action IN ('start', 'pause', 'resume', 'finish', 'produce', 'scrap', 'setup_start', 'setup_finish', 'close_shift', 'stopped', 'quality_check')",
            name="ck_productionlog_action",
        ),
        sa.ForeignKeyConstraint(
            ["line_id"],
            ["order_lines.id"],
        ),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_production_logs_line_id"), "production_logs", ["line_id"], unique=False
    )
    op.create_index(
        op.f("ix_production_logs_operator_id"), "production_logs", ["operator_id"], unique=False
    )
    op.create_index(
        op.f("ix_production_logs_order_id"), "production_logs", ["order_id"], unique=False
    )
    op.create_index(
        op.f("ix_production_logs_tenant_id"), "production_logs", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_production_logs_timestamp"), "production_logs", ["timestamp"], unique=False
    )
    op.create_index(
        "ix_productionlog_operator_ts",
        "production_logs",
        ["operator_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        "ix_productionlog_order_ts", "production_logs", ["order_id", "timestamp"], unique=False
    )
    op.create_index(
        "ix_productionlog_tenant_ts", "production_logs", ["tenant_id", "timestamp"], unique=False
    )

    # Inmutabilidad ISO 9001 (spec 04, regla 1): los logs de trazabilidad no
    # pueden modificarse ni borrarse. Trigger que bloquea UPDATE/DELETE.
    op.execute("""
        CREATE OR REPLACE FUNCTION production_logs_block_mutation()
        RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'production_logs es inmutable (ISO 9001): no se permite %',
                TG_OP;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_production_logs_immutable
        BEFORE UPDATE OR DELETE ON production_logs
        FOR EACH ROW EXECUTE FUNCTION production_logs_block_mutation();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS trg_production_logs_immutable ON production_logs;")
    op.execute("DROP FUNCTION IF EXISTS production_logs_block_mutation();")
    op.drop_index("ix_productionlog_tenant_ts", table_name="production_logs")
    op.drop_index("ix_productionlog_order_ts", table_name="production_logs")
    op.drop_index("ix_productionlog_operator_ts", table_name="production_logs")
    op.drop_index(op.f("ix_production_logs_timestamp"), table_name="production_logs")
    op.drop_index(op.f("ix_production_logs_tenant_id"), table_name="production_logs")
    op.drop_index(op.f("ix_production_logs_order_id"), table_name="production_logs")
    op.drop_index(op.f("ix_production_logs_operator_id"), table_name="production_logs")
    op.drop_index(op.f("ix_production_logs_line_id"), table_name="production_logs")
    op.drop_table("production_logs")
    # ### end Alembic commands ###
